chore: upgrade django 4.2 LTS (@W-14178534)
salesforce/django-declarative-apis pull request #148
Opened 2024-01-31 13:18 UTC by rohansroy

- [ ] Update CHANGELOG.md
- [ ] Update README.md (as needed)
- [ ] New dependencies were added to `pyproject.toml`
- [ ] `pip install` succeeds with a clean virtualenv
- [ ] There are new or modified tests that cover changes
- [ ] Test coverage is maintained or expanded

2024-01-31 15:23 UTC, bgrant commented
Would you mind adding to the CHANGELOG.md?

2024-01-31 15:27 UTC, bgrant commented
Testing with our service often uncovers problems with DDA changes that the unit tests don't.  I'll leave it to you if you want to go ahead and merge this change or wait until you do that testing.

2024-01-31 15:28 UTC, bgrant requested changes
Can you add a line to the CHANGELOG.md?

2024-02-07 15:03 UTC, bgrant commented on CHANGELOG.md
> +- [PR 148](https://github.com/salesforce/django-declarative-apis/pull/148) chore: upgrade django 4.2 LTS (@W-14178534)
Thank you for adding this.

It looks like we forgot to update this CHANGELOG the last time we released DDA.  This release contains the "ExpandableGeneric" filter type (and I assume the PRs before it):

[Release Django Declarative APIs v0.31.6 · salesforce/django-declarative-apis](https://github.com/salesforce/django-declarative-apis/releases/tag/v0.31.6)

This isn't your mistake, but would you mind fixing the CHANGELOG?

2024-02-07 15:05 UTC, bgrant commented on CHANGELOG.md
> +- [PR 148](https://github.com/salesforce/django-declarative-apis/pull/148) chore: upgrade django 4.2 LTS (@W-14178534)
You could potentially fix it in the PR when you make a release, so I'll go ahead and approve this PR.

2024-02-07 15:08 UTC, bgrant approved these changes
I found an issue with the CHANGELOG.  Would you mind fixing it when you update the CHANGELOG as part of making a new release?

2024-02-07 17:15 UTC, rohansroy commented
> I found an issue with the CHANGELOG. Would you mind fixing it when you update the CHANGELOG as part of making a new release?

will do, to save time i'll merge this and fix the changelog with the release PR.

2024-02-07 17:22 UTC, merged